services:
  windows:
    container_name: windows
    image: ghcr.io/dockur/windows
    environment:
      USERNAME: "liaox"
      PASSWORD: "password"
      RAM_SIZE: "16G"
      DISK_SIZE: "max"
      CPU_CORES: "max"
      LANGUAGE: "Chinese"
      REGION: "zh_CN"
      KEYBOARD: "cn" 
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: on-failure
    stop_grace_period: 2m
